# I changed database SQLite to PostgreSQL, so I removed some comments.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shrine_and_uppy_development

test:
  <<: *default
  database: shrine_and_uppy_development_test

production:
  <<: *default
  database: shrine_and_uppy_development_production
